version: "3"
services:
  # Web service layer
  apache:
    image: 'php:7.2-apache'
    container_name: php
    restart: always
    build:
      context: ./apache
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
  # Data persistence service layer
  mysql:
    image: mysql:5.7.20
  #  conainer_name: mysql
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

volumes:
  db_data: