<?php
$v_params = $this->getParams();
$o_contato = $v_params['o_contato'];
$v_telefones = $v_params['v_telefones'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Agenda Telef&ocirc;nica - Exemplo de MVC com PHP
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th colspan='3'>
					Contato
				</th>
			</tr>
			<tr>
				<th>
					ID
				</th>
				<th>
					Nome
				</th>
				<th>
					E-mail
				</th>
			</tr>
			<tr>
				<td>
					<?php echo $o_contato->getId()?>
				</td>
				<td>
					<?php echo $o_contato->getNome()?>
				</td>
				<td>
					<?php echo $o_contato->getEmail()?>
				</td>
			</tr>
		</table>
		<br />
		<table class='table_list' width="50%">
			<tr>
				<th colspan="5">
					Telefones
				</th>
			</tr>
			<tr>
				<th>
					ID
				</th>
				<th>
					DDD
				</th>
				<th>
					Telefone
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<?php
			foreach($v_telefones AS $o_telefone)
			{ 
				?>
				<tr>
					<td align="center">
						<?php echo $o_telefone->getId()?>
					</td>
					<td align="center">
						<?php echo $o_telefone->getDDD()?>
					</td>
					<td align="center">
						<?php echo $o_telefone->getTelefone()?>
					</td>
					<td align="center">
						<a href='?controle=Telefone&acao=apagarTelefone&in_con=<?php echo $o_contato->getId()?>&in_tel=<?php echo $o_telefone->getId()?>' class='bt_red'>Apagar</a>
					</td>
					<td align="center">
						<a href='?controle=Telefone&acao=manterTelefone&in_con=<?php echo $o_contato->getId()?>&in_tel=<?php echo $o_telefone->getId()?>' class='bt_blue'>Editar</a>
					</td>
				</tr>
				<?php
			} 
			?>
		</table>
		<br />
		<a href='?controle=Index' class='bt_red'>Voltar</a>
		<a href='?controle=Telefone&acao=manterTelefone&in_con=<?php echo $o_contato->getId()?>' class='bt_green'>Novo Telefone</a>
	</div>
</body>
</html>