<?php
$v_params = $this->getParams();
$o_contato = $v_params['o_contato'];
$o_telefone = $v_params['o_telefone'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Agenda Telef&ocirc;nica - Exemplo de MVC com PHP
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th colspan='3'>
					Contato
				</th>
			</tr>
			<tr>
				<th>
					ID
				</th>
				<th>
					Nome
				</th>
				<th>
					E-mail
				</th>
			</tr>
			<tr>
				<td>
					<?php echo $o_contato->getId()?>
				</td>
				<td>
					<?php echo $o_contato->getNome()?>
				</td>
				<td>
					<?php echo $o_contato->getEmail()?>
				</td>
			</tr>
		</table>
		<br />
		<form method='post'>
		<table class='table_list' width="40%">
			<tr>
				<th colspan="4">
					Telefones
				</th>
			</tr>
			<tr>
				<th>
					DDD
				</th>
				<th>
					Telefone
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<tr>
				<td align="center">
					<input type='text' name='in_ddd' value='<?php echo $o_telefone->getDDD()?>' size="5" maxlength="3">
				</td>
				<td align="center">
					<input type='text' name='in_telefone' value='<?php echo $o_telefone->getTelefone()?>'>
				</td>
				<td align="center">
					<a href='?controle=Telefone&acao=listaTelefones&in_con=<<?php echo $o_contato->getId()?>' class='bt_red'>Cancelar</a>
				</td>
				<td align="center">
					<input type='hidden' name='controle' value='Telefone'>
					<input type='hidden' name='acao' value='manterTelefone'>
					<input type='hidden' name='in_con' value='<?php echo $o_contato->getId()?>'>
					<input type='hidden' name='in_tel' value='<?php echo $o_telefone->getId()?>'>
					<button type='submit' class='bt_green'>Salvar</button>
				</td>
			</tr>
		</table>
		</form>
		<br />
		<a href='?controle=Telefone&acao=manterTelefone&in_con=<?php echo $o_contato->getId()?>' class='bt_green'>Novo Telefone</a>
	</div>
</body>
</html>